version: '3.8'

services:
  asimov-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asimov-algo
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: ["python", "Asimov.py"]
